#!/usr/bin/env node
// aggregate-index.mjs — builds the store's thin catalog from spoke repos' generated indexes.
// Central = routing hint only. Invalid/missing spoke index => RED entry + last-good data kept (stale:true).
// repos.json names are input-gated (unique, safe charset). --strict (CI mode): exit 1 if any repo is red.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execSync } from 'node:child_process';

const STRICT = process.argv.includes('--strict');
const ROOT = resolve(process.argv.filter(a => !a.startsWith('--'))[2] ?? '.');
const cfg = JSON.parse(readFileSync(join(ROOT, 'repos.json'), 'utf8'));
// repos.json: { "clones_dir": "..", "repos": [ { "name": "...", "url": "..." } ] }
const clonesDir = resolve(ROOT, cfg.clones_dir);

// input gate: names become filesystem paths and shell words — constrain at the boundary
const seen = new Set();
for (const r of cfg.repos) {
  if (!/^[a-z0-9][a-z0-9._-]*$/.test(r.name)) { console.error(`✗ repos.json: invalid repo name "${r.name}" (allowed: [a-z0-9._-], no leading dot/dash)`); process.exit(2); }
  if (seen.has(r.name)) { console.error(`✗ repos.json: duplicate repo name "${r.name}"`); process.exit(2); }
  seen.add(r.name);
}

// keep-last-good: carry a red repo's previous entry, marked stale, instead of dropping it
const prevPath = join(ROOT, 'catalog.json');
const prev = existsSync(prevPath) ? JSON.parse(readFileSync(prevPath, 'utf8')) : { entries: [] };
const prevByName = new Map((prev.entries ?? []).map(e => [e.name, e]));

const entries = [], red = [];
const byName = (a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0); // byte-wise, locale-independent
for (const r of [...cfg.repos].sort(byName)) {
  const repoDir = join(clonesDir, r.name);
  const idxPath = join(repoDir, 'openspec', 'index.json');
  try {
    if (!existsSync(repoDir)) throw new Error('clone missing — run tools/sync-repos.sh');
    if (!existsSync(idxPath)) throw new Error('openspec/index.json missing — repo not onboarded or index not generated');
    const idx = JSON.parse(readFileSync(idxPath, 'utf8'));
    if (!Array.isArray(idx.capabilities)) throw new Error('index.json has no capabilities[] — regenerate in the repo');
    const head = execSync('git rev-parse --short HEAD', { cwd: repoDir }).toString().trim();
    entries.push({ name: r.name, url: r.url, head, digest: idx.source_digest, capabilities: idx.capabilities.map(c => ({ id: c.id, title: c.title, summary: c.summary })) });
  } catch (e) {
    red.push({ name: r.name, reason: e.message });
    const lastGood = prevByName.get(r.name);
    if (lastGood) entries.push({ ...lastGood, stale: true, stale_reason: e.message });
  }
}
entries.sort(byName);

const catalog = { schema_version: 1, entries, red };
writeFileSync(join(ROOT, 'catalog.json'), JSON.stringify(catalog, null, 2) + '\n');

const md = [
  '# System catalog',
  '',
  '> GENERATED by tools/aggregate-index.mjs — routing hints only. The repo index is the authority; the repo itself outranks its index.',
  '',
  ...(red.length ? ['## 🔴 RED — fix before trusting the catalog', '', ...red.map(x => `- **${x.name}**: ${x.reason}`), ''] : []),
  ...entries.flatMap(e => [
    `## ${e.name}${e.stale ? ' ⚠ STALE (last-good data; see RED above)' : ''}`,
    '',
    `repo: ${e.url} · HEAD \`${e.head}\` · digest \`${e.digest}\``,
    '',
    ...e.capabilities.map(c => `- **${c.id}** — ${c.summary}`),
    '',
  ]),
].join('\n');
writeFileSync(join(ROOT, 'catalog.md'), md);

console.log(`✓ catalog: ${entries.length} entries (${entries.filter(e => e.stale).length} stale), ${red.length} red`);
if (red.length) {
  for (const x of red) console.error(`  🔴 ${x.name}: ${x.reason}`);
  if (STRICT) process.exit(1);
}
